name: example
on: 
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: write
  
jobs:

  pr-init:
    if: ${{ github.event }}
    runs-on: ubuntu-latest
    name: test
    
    steps:

      - name: Check temperature
        id: rhein
        uses: tobiasdenzler-nag/rhein-schwumm-action@main

      # add pr information
      # https://github.com/marketplace/actions/sticky-pull-request-comment
      - name: Add init message
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test
          message: |
            Die aktuelli Rhy Temperatur isch ${{ steps.rhein.outputs.temperature }}. Viel Spass bim Baade!
